 This file was autogenerated by Stack.
# You should not edit this file by hand.
# For more information, please see the documentation at:
#   https://docs.haskellstack.org/en/stable/lock_files

packages:
- completed:
    hackage: turtle-1.5.19@sha256:d801bbee7bd45259be33d9e9a3216b1ad0ea58ec2c78bd1760ffcc225a961cfc,5010
    pantry-tree:
      size: 1114
      sha256: b3b4a6e53a7c35d5c748f62b01c5e57a6a4a89d0f14a03af742cd2bddbe7fae4
  original:
    hackage: turtle-1.5.19
- completed:
    hackage: directory-1.3.6.1@sha256:3dc9c69c8e09ec95a7a45c6d06abe0f0d2f604439c37e5f88e5a6c335b088d71,2810
    pantry-tree:
      size: 3433
      sha256: 9247d0e7cfbf9946b922d23bd56a6b765cdb91f71d72f8ae6ed22c94dbd9f1db
  original:
    hackage: directory-1.3.6.1
- completed:
    hackage: process-1.6.10.0@sha256:c0d2d8adaca7cea7ceaa60e67b61c775dc03727b83bdb1c97aa8cbeac9f5dd84,2469
    pantry-tree:
      size: 1211
      sha256: 6e90778b5105753d7de0f7a0c502dadf8f04825f17a36186aa801e56ef7ca206
  original:
    hackage: process-1.6.10.0
snapshots:
- completed:
    size: 567338
    url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/10/2.yaml
    sha256: 092cce7d8bb031346c99d4847906457edc1e89815e7f4477d3c9a96386e70144
  original: lts-10.2
